//! Cargo vendor management for offline builds on Redox OS.
//!
//! Manages vendored crate dependencies for `cargo build --offline`.
//! Source bundles with pre-vendored deps are pushed to the guest via
//! the virtio-fs shared filesystem or included in the disk image.
//!
//! Usage:
//!   snix vendor setup <vendor-dir>    — create .cargo/config.toml for offline builds
//!   snix vendor info <vendor-dir>     — show vendored crate count and sizes
//!   snix vendor check <vendor-dir>    — verify vendor directory integrity
//!   snix vendor link <store-path>     — symlink a store-path source bundle for building

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

// ── Setup ──────────────────────────────────────────────────────────────────

/// Create or update `.cargo/config.toml` for offline vendored builds.
///
/// Writes a cargo config that:
/// - Replaces crates-io with the local vendor directory
/// - Enables offline mode
/// - Optionally sets the build target
pub fn setup(
    vendor_dir: &str,
    project_dir: Option<&str>,
    target: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    let vendor_path = Path::new(vendor_dir);
    if !vendor_path.is_dir() {
        return Err(format!("vendor directory not found: {vendor_dir}").into());
    }

    let project = project_dir
        .map(PathBuf::from)
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));

    let cargo_dir = project.join(".cargo");
    fs::create_dir_all(&cargo_dir)?;

    let config_path = cargo_dir.join("config.toml");

    // Build the config content
    let mut config = String::new();
    config.push_str("# Generated by snix vendor setup\n");
    config.push_str("[source.crates-io]\n");
    config.push_str("replace-with = \"vendored-sources\"\n\n");
    config.push_str("[source.vendored-sources]\n");
    config.push_str(&format!("directory = \"{vendor_dir}\"\n\n"));
    config.push_str("[net]\n");
    config.push_str("offline = true\n");

    if let Some(t) = target {
        config.push_str(&format!("\n[build]\ntarget = \"{t}\"\n"));
    }

    fs::write(&config_path, &config)?;
    println!("wrote {}", config_path.display());
    println!("vendor: {vendor_dir}");

    let count = count_crates(vendor_path)?;
    println!("crates: {count}");

    Ok(())
}

// ── Info ────────────────────────────────────────────────────────────────────

/// Show information about a vendor directory.
pub fn info(vendor_dir: &str) -> Result<(), Box<dyn std::error::Error>> {
    let vendor_path = Path::new(vendor_dir);
    if !vendor_path.is_dir() {
        return Err(format!("vendor directory not found: {vendor_dir}").into());
    }

    let crates = list_crates(vendor_path)?;
    let total_size: u64 = crates.values().sum();

    println!("Vendor directory: {vendor_dir}");
    println!("Crates: {}", crates.len());
    println!("Total size: {}", human_size(total_size));
    println!();

    for (name, size) in &crates {
        println!("  {name:<40} {}", human_size(*size));
    }

    Ok(())
}

// ── Check ──────────────────────────────────────────────────────────────────

/// Verify vendor directory integrity.
///
/// Checks that each crate directory has a valid `.cargo-checksum.json`.
pub fn check(vendor_dir: &str) -> Result<(), Box<dyn std::error::Error>> {
    let vendor_path = Path::new(vendor_dir);
    if !vendor_path.is_dir() {
        return Err(format!("vendor directory not found: {vendor_dir}").into());
    }

    let mut ok = 0u32;
    let mut missing_checksum = 0u32;
    let mut errors = Vec::new();

    for entry in fs::read_dir(vendor_path)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }

        let name = entry.file_name().to_string_lossy().to_string();
        let checksum_path = entry.path().join(".cargo-checksum.json");

        if !checksum_path.exists() {
            missing_checksum += 1;
            errors.push(format!("  {name}: missing .cargo-checksum.json"));
            continue;
        }

        // Try to parse the checksum file
        match fs::read_to_string(&checksum_path) {
            Ok(content) => {
                if serde_json::from_str::<serde_json::Value>(&content).is_err() {
                    errors.push(format!("  {name}: corrupt .cargo-checksum.json"));
                } else {
                    ok += 1;
                }
            }
            Err(e) => {
                errors.push(format!("  {name}: cannot read checksum: {e}"));
            }
        }
    }

    println!("Vendor directory: {vendor_dir}");
    println!("  Valid crates:    {ok}");

    if missing_checksum > 0 {
        println!("  Missing checksum: {missing_checksum}");
    }

    if !errors.is_empty() {
        println!();
        println!("Issues:");
        for err in &errors {
            println!("{err}");
        }
        return Err(format!("{} issue(s) found", errors.len()).into());
    }

    println!("  Status:          OK");
    Ok(())
}

// ── Link ───────────────────────────────────────────────────────────────────

/// Symlink a store-path source bundle into a working directory for building.
///
/// Source bundles (from `snix-source-bundle.nix`) are in the Nix store
/// and read-only. This creates a writable working copy with the vendor
/// directory and cargo config ready to go.
pub fn link(
    store_path: &str,
    dest: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    let src = Path::new(store_path);
    if !src.is_dir() {
        return Err(format!("source bundle not found: {store_path}").into());
    }

    // Determine destination
    let dest_path = match dest {
        Some(d) => PathBuf::from(d),
        None => {
            let name = src
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_else(|| "source".to_string());
            // Strip the hash prefix from store path names
            let clean_name = if name.len() > 33 {
                &name[33..] // Skip "hash-" prefix
            } else {
                &name
            };
            PathBuf::from(clean_name)
        }
    };

    if dest_path.exists() {
        return Err(format!("destination already exists: {}", dest_path.display()).into());
    }

    // Create the destination directory
    fs::create_dir_all(&dest_path)?;

    // Symlink or copy contents (symlinks for large files, copies for config)
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let name = entry.file_name();
        let src_entry = entry.path();
        let dest_entry = dest_path.join(&name);

        if name == ".cargo" || name == "Cargo.toml" || name == "Cargo.lock" {
            // Copy small config files (they might need to be writable)
            copy_recursive(&src_entry, &dest_entry)?;
        } else {
            // Symlink large directories (src/, vendor/, etc.)
            std::os::unix::fs::symlink(&src_entry, &dest_entry)?;
        }
    }

    println!("linked: {store_path}");
    println!("   to:  {}", dest_path.display());
    println!();
    println!("To build:");
    println!("  cd {}", dest_path.display());
    println!("  cargo build --offline");

    Ok(())
}

// ── CLI Entry Point ────────────────────────────────────────────────────────

pub fn run(command: &VendorCommand) -> Result<(), Box<dyn std::error::Error>> {
    match command {
        VendorCommand::Setup {
            vendor_dir,
            project_dir,
            target,
        } => setup(vendor_dir, project_dir.as_deref(), target.as_deref()),
        VendorCommand::Info { vendor_dir } => info(vendor_dir),
        VendorCommand::Check { vendor_dir } => check(vendor_dir),
        VendorCommand::Link { store_path, dest } => {
            link(store_path, dest.as_deref())
        }
    }
}

// ── CLI Types ──────────────────────────────────────────────────────────────

use clap::Subcommand;

#[derive(Subcommand)]
pub enum VendorCommand {
    /// Create .cargo/config.toml for offline vendored builds
    Setup {
        /// Path to the vendor directory
        vendor_dir: String,

        /// Project directory (default: current dir)
        #[arg(short, long)]
        project_dir: Option<String>,

        /// Build target (e.g., x86_64-unknown-redox)
        #[arg(short, long)]
        target: Option<String>,
    },

    /// Show vendored crate information
    Info {
        /// Path to the vendor directory
        vendor_dir: String,
    },

    /// Verify vendor directory integrity
    Check {
        /// Path to the vendor directory
        vendor_dir: String,
    },

    /// Link a store-path source bundle for local building
    Link {
        /// Store path to source bundle (e.g., /nix/store/abc-snix-source-bundle)
        store_path: String,

        /// Destination directory (default: derived from store path name)
        #[arg(short, long)]
        dest: Option<String>,
    },
}

// ── Helpers ────────────────────────────────────────────────────────────────

fn count_crates(vendor_dir: &Path) -> io::Result<u32> {
    let mut count = 0;
    for entry in fs::read_dir(vendor_dir)? {
        let entry = entry?;
        if entry.file_type()?.is_dir() {
            count += 1;
        }
    }
    Ok(count)
}

fn list_crates(vendor_dir: &Path) -> io::Result<BTreeMap<String, u64>> {
    let mut crates = BTreeMap::new();
    for entry in fs::read_dir(vendor_dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        let size = dir_size(&entry.path())?;
        crates.insert(name, size);
    }
    Ok(crates)
}

fn dir_size(path: &Path) -> io::Result<u64> {
    let mut total = 0;
    if path.is_file() {
        return Ok(path.metadata()?.len());
    }
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let meta = entry.metadata()?;
        if meta.is_file() {
            total += meta.len();
        } else if meta.is_dir() {
            total += dir_size(&entry.path())?;
        }
    }
    Ok(total)
}

fn copy_recursive(src: &Path, dest: &Path) -> io::Result<()> {
    if src.is_file() {
        fs::copy(src, dest)?;
    } else if src.is_dir() {
        fs::create_dir_all(dest)?;
        for entry in fs::read_dir(src)? {
            let entry = entry?;
            copy_recursive(&entry.path(), &dest.join(entry.file_name()))?;
        }
    }
    Ok(())
}

fn human_size(bytes: u64) -> String {
    const KB: u64 = 1024;
    const MB: u64 = 1024 * KB;
    if bytes >= MB {
        format!("{:.1} MB", bytes as f64 / MB as f64)
    } else if bytes >= KB {
        format!("{:.1} KB", bytes as f64 / KB as f64)
    } else {
        format!("{bytes} B")
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_vendor(tmp: &TempDir) -> PathBuf {
        let vendor = tmp.path().join("vendor");
        fs::create_dir(&vendor).unwrap();

        // Create fake crate directories with checksums
        for name in &["serde-1.0.200", "clap-4.5.0", "sha2-0.10.8"] {
            let crate_dir = vendor.join(name);
            fs::create_dir(&crate_dir).unwrap();
            fs::write(crate_dir.join("Cargo.toml"), "[package]\nname = \"test\"").unwrap();
            fs::write(
                crate_dir.join(".cargo-checksum.json"),
                r#"{"files": {}, "package": "abc123"}"#,
            )
            .unwrap();
        }

        vendor
    }

    #[test]
    fn setup_creates_config() {
        let tmp = TempDir::new().unwrap();
        let vendor = make_vendor(&tmp);
        let project = tmp.path().join("project");
        fs::create_dir(&project).unwrap();

        setup(
            vendor.to_str().unwrap(),
            Some(project.to_str().unwrap()),
            None,
        )
        .unwrap();

        let config = project.join(".cargo/config.toml");
        assert!(config.exists());

        let content = fs::read_to_string(&config).unwrap();
        assert!(content.contains("[source.crates-io]"));
        assert!(content.contains("replace-with = \"vendored-sources\""));
        assert!(content.contains(&vendor.to_string_lossy().to_string()));
        assert!(content.contains("offline = true"));
    }

    #[test]
    fn setup_with_target() {
        let tmp = TempDir::new().unwrap();
        let vendor = make_vendor(&tmp);
        let project = tmp.path().join("project");
        fs::create_dir(&project).unwrap();

        setup(
            vendor.to_str().unwrap(),
            Some(project.to_str().unwrap()),
            Some("x86_64-unknown-redox"),
        )
        .unwrap();

        let content = fs::read_to_string(project.join(".cargo/config.toml")).unwrap();
        assert!(content.contains("target = \"x86_64-unknown-redox\""));
    }

    #[test]
    fn setup_missing_vendor_errors() {
        let result = setup("/nonexistent/vendor", None, None);
        assert!(result.is_err());
    }

    #[test]
    fn info_shows_crates() {
        let tmp = TempDir::new().unwrap();
        let vendor = make_vendor(&tmp);

        // info() prints to stdout; just verify it doesn't error
        info(vendor.to_str().unwrap()).unwrap();
    }

    #[test]
    fn info_missing_vendor_errors() {
        let result = info("/nonexistent/vendor");
        assert!(result.is_err());
    }

    #[test]
    fn check_valid_vendor() {
        let tmp = TempDir::new().unwrap();
        let vendor = make_vendor(&tmp);

        check(vendor.to_str().unwrap()).unwrap();
    }

    #[test]
    fn check_missing_checksum() {
        let tmp = TempDir::new().unwrap();
        let vendor = tmp.path().join("vendor");
        fs::create_dir(&vendor).unwrap();

        let crate_dir = vendor.join("bad-crate-1.0");
        fs::create_dir(&crate_dir).unwrap();
        // No .cargo-checksum.json

        let result = check(vendor.to_str().unwrap());
        assert!(result.is_err());
    }

    #[test]
    fn check_corrupt_checksum() {
        let tmp = TempDir::new().unwrap();
        let vendor = tmp.path().join("vendor");
        fs::create_dir(&vendor).unwrap();

        let crate_dir = vendor.join("corrupt-1.0");
        fs::create_dir(&crate_dir).unwrap();
        fs::write(crate_dir.join(".cargo-checksum.json"), "not json").unwrap();

        let result = check(vendor.to_str().unwrap());
        assert!(result.is_err());
    }

    #[test]
    fn link_creates_working_copy() {
        let tmp = TempDir::new().unwrap();

        // Create a fake source bundle
        let bundle = tmp.path().join("source-bundle");
        fs::create_dir(&bundle).unwrap();
        fs::write(bundle.join("Cargo.toml"), "[package]\nname = \"test\"").unwrap();
        fs::write(bundle.join("Cargo.lock"), "").unwrap();

        let cargo_dir = bundle.join(".cargo");
        fs::create_dir(&cargo_dir).unwrap();
        fs::write(cargo_dir.join("config.toml"), "[net]\noffline = true").unwrap();

        let src_dir = bundle.join("src");
        fs::create_dir(&src_dir).unwrap();
        fs::write(src_dir.join("main.rs"), "fn main() {}").unwrap();

        // Link to a dest
        let dest = tmp.path().join("work");
        link(bundle.to_str().unwrap(), Some(dest.to_str().unwrap())).unwrap();

        // Config files should be copied
        assert!(dest.join("Cargo.toml").exists());
        assert!(dest.join("Cargo.lock").exists());
        assert!(dest.join(".cargo/config.toml").exists());

        // Source directory should be symlinked
        assert!(dest.join("src").symlink_metadata().unwrap().is_symlink());
    }

    #[test]
    fn link_dest_exists_errors() {
        let tmp = TempDir::new().unwrap();
        let bundle = tmp.path().join("bundle");
        fs::create_dir(&bundle).unwrap();
        let dest = tmp.path().join("exists");
        fs::create_dir(&dest).unwrap();

        let result = link(bundle.to_str().unwrap(), Some(dest.to_str().unwrap()));
        assert!(result.is_err());
    }

    #[test]
    fn count_crates_works() {
        let tmp = TempDir::new().unwrap();
        let vendor = make_vendor(&tmp);
        assert_eq!(count_crates(&vendor).unwrap(), 3);
    }

    #[test]
    fn list_crates_sorted() {
        let tmp = TempDir::new().unwrap();
        let vendor = make_vendor(&tmp);
        let crates = list_crates(&vendor).unwrap();
        assert_eq!(crates.len(), 3);

        let names: Vec<&String> = crates.keys().collect();
        assert!(names[0] < names[1]); // BTreeMap is sorted
    }

    #[test]
    fn human_size_formatting() {
        assert_eq!(human_size(0), "0 B");
        assert_eq!(human_size(512), "512 B");
        assert_eq!(human_size(1024), "1.0 KB");
        assert_eq!(human_size(1048576), "1.0 MB");
    }

    #[test]
    fn copy_recursive_works() {
        let tmp = TempDir::new().unwrap();
        let src = tmp.path().join("src");
        fs::create_dir_all(src.join("sub")).unwrap();
        fs::write(src.join("a.txt"), "alpha").unwrap();
        fs::write(src.join("sub/b.txt"), "bravo").unwrap();

        let dest = tmp.path().join("dest");
        copy_recursive(&src, &dest).unwrap();

        assert_eq!(fs::read_to_string(dest.join("a.txt")).unwrap(), "alpha");
        assert_eq!(fs::read_to_string(dest.join("sub/b.txt")).unwrap(), "bravo");
    }
}
