# RedoxOS Environment Configuration
#
# Manages system-wide environment:
#   - System packages (binaries available in /bin and /usr/bin)
#   - Environment variables (exported in /etc/profile)
#   - Ion shell aliases (defined in /etc/profile)
#   - Shell initialization commands
#
# This module also declares the critical `redox.generatedFiles` option
# that ALL modules use to contribute file generation fragments.
# This is the "config bubbling" pattern - modules write to generatedFiles,
# and the activation layer (build/rootfs.nix) reads from it.

{
  config,
  lib,
  pkgs,
  hostPkgs,
  redoxSystemLib,
  ...
}:

let
  inherit (lib)
    mkOption
    mkDefault
    types
    concatStringsSep
    mapAttrsToList
    optionalString
    ;

  cfg = config.redox.environment;

  # Generate Ion shell alias definitions
  # Ion syntax: alias name = "command"
  aliasLines = concatStringsSep "\n" (
    mapAttrsToList (name: value: ''alias ${name} = "${value}"'') cfg.shellAliases
  );

  # Generate environment variable exports
  # Ion syntax: export VAR value
  varLines = concatStringsSep "\n" (
    mapAttrsToList (name: value: "export ${name} ${value}") cfg.variables
  );

  # Complete /etc/profile content
  profileContent = ''
    # RedoxOS System Profile
    # Generated by redox-system environment module
    # This file is sourced by Ion shell on login

    # Environment variables
    ${varLines}

    # Shell aliases
    ${aliasLines}

    # Custom initialization
    ${cfg.shellInit}
  '';

in
{
  options.redox.environment = {
    systemPackages = mkOption {
      type = types.listOf types.package;
      default = [ ];
      description = ''
        System-wide packages. Binaries from these packages are made
        available in /bin and /usr/bin.
      '';
    };

    shellAliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
      example = {
        ll = "ls -l";
        la = "ls -la";
      };
      description = ''
        Ion shell aliases defined in /etc/profile.
        Ion syntax: alias name = "command"
      '';
    };

    variables = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = ''
        Environment variables exported in /etc/profile.
        Ion syntax: export VAR value
      '';
    };

    shellInit = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Extra commands to add to /etc/profile.
        Written as raw Ion shell script.
      '';
    };
  };

  # CRITICAL: Declare the shared generatedFiles option that ALL modules write to
  options.redox.generatedFiles = mkOption {
    type = types.attrsOf (
      types.submodule {
        options = {
          text = mkOption {
            type = types.lines;
            description = "File content";
          };

          mode = mkOption {
            type = types.str;
            default = "0644";
            description = "File permission mode (octal string)";
          };
        };
      }
    );
    default = { };
    description = ''
      Generated configuration files. This is the central collection point
      for all file generation across all modules. The activation/build layer
      reads this to create the actual filesystem.

      Format: attrset where keys are file paths (relative to rootfs)
      and values are { text, mode }.

      Example:
        redox.generatedFiles."etc/hostname" = {
          text = "myredox\n";
          mode = "0644";
        };
    '';
  };

  config = {
    # Default environment variables
    redox.environment.variables = {
      PATH = mkDefault "/bin:/usr/bin";
      HOME = mkDefault "/root";
      USER = mkDefault "root";
      SHELL = mkDefault "/bin/ion";
      TERM = mkDefault "xterm-256color";
    };

    # Default shell aliases (common conveniences)
    redox.environment.shellAliases = {
      ls = mkDefault "ls --color=auto";
      grep = mkDefault "grep --color=auto";
    };

    # Generate /etc/profile
    redox.generatedFiles."etc/profile" = {
      text = profileContent;
      mode = "0644";
    };
  };
}
