# Sodium - vi-like text editor for Redox OS
#
# This package requires special handling because:
# 1. The sodium-src lacks a Cargo.lock file (uses orbclient's structure)
# 2. It requires patching orbclient to remove SDL2 dependency
# 3. It needs libredox vendor for orbclient dependency
#
# Usage:
#   sodium = import ./sodium.nix {
#     inherit pkgs lib rustToolchain sysrootVendor redoxTarget relibc stubLibs;
#     inherit sodium-src orbclient-src;
#   };

{
  pkgs,
  lib,
  rustToolchain,
  sysrootVendor,
  redoxTarget,
  relibc,
  stubLibs,
  sodium-src,
  orbclient-src,
}:

let
  # Create a synthetic package to vendor libredox (orbclient's Redox dependency)
  sodiumDepsSource = pkgs.runCommand "sodium-deps-source" { } ''
        mkdir -p $out/src
        echo "fn main() {}" > $out/src/main.rs
        cat > $out/Cargo.toml << 'TOML'
    [package]
    name = "sodium-deps"
    version = "0.1.0"
    edition = "2021"

    [dependencies]
    libredox = "0.1"
    TOML
        cat > $out/Cargo.lock << 'LOCK'
    # This file is automatically @generated by Cargo.
    # It is not intended for manual editing.
    version = 4

    [[package]]
    name = "bitflags"
    version = "2.9.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "1b8e56985ec62d17e9c1001dc89c88ecd7dc08e47eba5ec7c29c7b5eeecde967"

    [[package]]
    name = "libc"
    version = "0.2.172"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "d750af042f7ef4f724306de029d18836c26c1765a54a6a3f094cbd23a7267ffa"

    [[package]]
    name = "libredox"
    version = "0.1.12"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "3d0b95e02c851351f877147b7deea7b1afb1df71b63aa5f8270716e0c5720616"
    dependencies = [
     "bitflags",
     "libc",
     "redox_syscall",
    ]

    [[package]]
    name = "redox_syscall"
    version = "0.7.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "49f3fe0889e69e2ae9e41f4d6c4c0181701d00e4697b356fb1f74173a5e0ee27"
    dependencies = [
     "bitflags",
    ]

    [[package]]
    name = "sodium-deps"
    version = "0.1.0"
    dependencies = [
     "libredox",
    ]
    LOCK
  '';

  # Vendor libredox dependencies
  sodiumVendor = pkgs.rustPlatform.fetchCargoVendor {
    name = "sodium-deps-vendor";
    src = sodiumDepsSource;
    hash = "sha256-yuxAB+9CZHCz/bAKPD82+8LfU3vgVWU6KeTVVk1JcO8=";
  };

  # Python script for regenerating checksums (no leading indentation for heredoc)
  checksumScript = ''
    import json
    import hashlib
    from pathlib import Path

    vendor_dir = Path("vendor-combined")
    for crate_dir in vendor_dir.iterdir():
        if not crate_dir.is_dir():
            continue
        checksum_file = crate_dir / ".cargo-checksum.json"
        if not checksum_file.exists():
            continue
        with open(checksum_file) as f:
            existing = json.load(f)
        pkg_hash = existing.get("package")
        files = {}
        for file_path in sorted(crate_dir.rglob("*")):
            if file_path.is_file() and file_path.name != ".cargo-checksum.json":
                rel_path = str(file_path.relative_to(crate_dir))
                with open(file_path, "rb") as f:
                    sha = hashlib.sha256(f.read()).hexdigest()
                files[rel_path] = sha
        new_data = {"files": files}
        if pkg_hash:
            new_data["package"] = pkg_hash
        with open(checksum_file, "w") as f:
            json.dump(new_data, f)
  '';

in
pkgs.stdenv.mkDerivation {
  pname = "sodium";
  version = "unstable";

  dontUnpack = true;

  nativeBuildInputs = [
    rustToolchain
    pkgs.llvmPackages.clang
    pkgs.llvmPackages.bintools
    pkgs.llvmPackages.lld
    pkgs.python3
  ];

  buildInputs = [ relibc ];

  TARGET = redoxTarget;
  RUST_SRC_PATH = "${rustToolchain}/lib/rustlib/src/rust/library";

  configurePhase = ''
            runHook preConfigure

            cp -r ${sodium-src}/* .
            chmod -R u+w .

            # Copy orbclient and patch it to remove sdl2 patch section (not needed for Redox)
            mkdir -p orbclient-patched
            cp -r ${orbclient-src}/* orbclient-patched/
            chmod -R u+w orbclient-patched/

            # Remove the [patch.crates-io] section entirely (not needed for Redox target)
            sed -i '/\[patch\.crates-io\]/,$d' orbclient-patched/Cargo.toml

            # Patch Cargo.toml to use patched orbclient without default features (no SDL)
            substituteInPlace Cargo.toml \
              --replace-fail 'orbclient = "0.3"' 'orbclient = { path = "orbclient-patched", default-features = false }'

            # Merge libredox vendor + sysroot vendors
            mkdir -p vendor-combined

            get_version() {
              grep '^version = ' "$1/Cargo.toml" | head -1 | sed 's/version = "\(.*\)"/\1/'
            }

            # Copy libredox vendor (flat structure from fetchCargoVendor)
            for crate in ${sodiumVendor}/*/; do
              crate_name=$(basename "$crate")
              if [ -d "$crate" ]; then
                cp -rL "$crate" "vendor-combined/$crate_name"
              fi
            done
            chmod -R u+w vendor-combined/

            # Copy sysroot vendor
            for crate in ${sysrootVendor}/*/; do
              crate_name=$(basename "$crate")
              if [ ! -d "$crate" ]; then
                continue
              fi
              if [ -d "vendor-combined/$crate_name" ]; then
                base_version=$(get_version "vendor-combined/$crate_name")
                sysroot_version=$(get_version "$crate")
                if [ "$base_version" != "$sysroot_version" ]; then
                  versioned_name="$crate_name-$sysroot_version"
                  if [ ! -d "vendor-combined/$versioned_name" ]; then
                    cp -rL "$crate" "vendor-combined/$versioned_name"
                  fi
                fi
              else
                cp -rL "$crate" "vendor-combined/$crate_name"
              fi
            done
            chmod -R u+w vendor-combined/

            # Regenerate checksums
            ${pkgs.python3}/bin/python3 << 'PYTHON_CHECKSUM'
    ${checksumScript}
    PYTHON_CHECKSUM

            mkdir -p .cargo
            cat > .cargo/config.toml << 'CARGOCONF'
    [source.crates-io]
    replace-with = "vendored-sources"

    [source.vendored-sources]
    directory = "vendor-combined"

    [net]
    offline = true

    [build]
    target = "${redoxTarget}"

    [target.${redoxTarget}]
    linker = "${pkgs.llvmPackages.clang-unwrapped}/bin/clang"

    [profile.release]
    panic = "abort"
    CARGOCONF

            runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild

    export HOME=$(mktemp -d)

    export CARGO_TARGET_X86_64_UNKNOWN_REDOX_RUSTFLAGS="-C target-cpu=x86-64 -L ${relibc}/${redoxTarget}/lib -L ${stubLibs}/lib -C panic=abort -C linker=${pkgs.llvmPackages.clang-unwrapped}/bin/clang -C link-arg=-nostdlib -C link-arg=-static -C link-arg=--target=${redoxTarget} -C link-arg=${relibc}/${redoxTarget}/lib/crt0.o -C link-arg=${relibc}/${redoxTarget}/lib/crti.o -C link-arg=${relibc}/${redoxTarget}/lib/crtn.o -C link-arg=-Wl,--allow-multiple-definition"

    # Build sodium with ansi feature (terminal mode, not orbital GUI)
    cargo build \
      --bin sodium \
      --target ${redoxTarget} \
      --release \
      --no-default-features \
      --features ansi \
      -Z build-std=core,alloc,std,panic_abort \
      -Z build-std-features=compiler-builtins-mem

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp target/${redoxTarget}/release/sodium $out/bin/
    runHook postInstall
  '';

  meta = with lib; {
    description = "Sodium: A vi-like text editor for Redox OS";
    homepage = "https://gitlab.redox-os.org/redox-os/sodium";
    license = licenses.mit;
  };
}
